### ISSUE TITLE
java.lang.IllegalArgumentException at getVoices:172

### ISSUE THREAD

**Issue by whitmer** [macdonst/SpeechSynthesisPlugin#13]
I have a user on a Galaxy Tab 4 getting the following exception. I can't reproduce it on my Tab 4, or any other device, but I'm thinking about adding a try catch block outside that line so the app at least won't crash on them. I'm not smart enough to know what's really going on :-/.

java.lang.IllegalArgumentException: 
  at android.os.Parcel.readException(Parcel.java:1544)
  at android.os.Parcel.readException(Parcel.java:1493)
  at android.speech.tts.ITextToSpeechService$Stub$Proxy.getVoices(ITextToSpeechService.java:796)
  at android.speech.tts.TextToSpeech$15.run(TextToSpeech.java:1667)
  at android.speech.tts.TextToSpeech$15.run(TextToSpeech.java:1664)
  at android.speech.tts.TextToSpeech$Connection.runAction(TextToSpeech.java:2310)
  at android.speech.tts.TextToSpeech.runAction(TextToSpeech.java:747)
  at android.speech.tts.TextToSpeech.runAction(TextToSpeech.java:737)
  at android.speech.tts.TextToSpeech.getVoices(TextToSpeech.java:1664)
  at org.apache.cordova.speech.SpeechSynthesis.getVoices(SpeechSynthesis.java:172)
  at org.apache.cordova.speech.SpeechSynthesis.onInit(SpeechSynthesis.java:258)
  at android.speech.tts.TextToSpeech.dispatchOnInit(TextToSpeech.java:820)
  at android.speech.tts.TextToSpeech.access$1500(TextToSpeech.java:59)
  at android.speech.tts.TextToSpeech$Connection$SetupConnectionAsyncTask.onPostExecute(TextToSpeech.java:2224)
  at android.speech.tts.TextToSpeech$Connection$SetupConnectionAsyncTask.onPostExecute(TextToSpeech.java:2179)
  at android.os.AsyncTask.finish(AsyncTask.java:632)
  at android.os.AsyncTask.access$600(AsyncTask.java:177)
  at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:645)
  at android.os.Handler.dispatchMessage(Handler.java:102)
  at android.os.Looper.loop(Looper.java:145)
  at android.app.ActivityThread.main(ActivityThread.java:6134)
  at java.lang.reflect.Method.invoke(Native Method:0)
  at java.lang.reflect.Method.invoke(Method.java:372)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)

**Comment by whitmer** [comment]
It looks like these might be related: 

https://stackoverflow.com/questions/43391514/tts-causing-illegalargumentexceptioninvalid-int-os-during-oninit-in-some-sam

http://developer.samsung.com/forum/board/thread/view.do?boardName=SDK&messageId=295016

**Comment by arsen91** [comment]
I have the same issue with our users. Galaxy Tab3 7.0 on Android 4.4

Any plans to fix or merge this workaround?

**Comment by arsen91** [comment]
In case anyone would ever need to support older Android on Samsungs [here](https://github.com/Geotab/SpeechSynthesisPlugin/commits/master) is our fork with the fixed issue on older Android versions (last 3 commits from me). The problem occurs only on Android 4.0.0 - 5.1.0 where users have both text to speech engines: Samsung and Google. Samsung is chosen as a default one and it breaks the app, since it doesn't have certain methods. The fix actually is to check if Google TTS is installed and use it in the application, otherwise just ignore the code that fails. It still speaks and seems to work fine when we ignore broken methods.
